# Run the development build

services:
  frontend:
    image: node:latest
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  backend:
    image: rust:latest
    working_dir: /app/backend/dev
    volumes:
      - ./backend:/app/backend
    environment:
      - ROCKET_ADDRESS=0.0.0.0
    command: sh -c "cargo install cargo-watch && cargo watch -x run"
